//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalEntry()
        {
            this.JournalEntryLines = new HashSet<JournalEntryLine>();
        }
    
        public int Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Description { get; set; }
        public string ReferenceNo { get; set; }
        public bool Posted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalEntryLine> JournalEntryLines { get; set; }
    }
}
