//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public decimal PaidAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsAdvance { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
